routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@index');

Route::get('/{uri}.php', 'PageController@show');

Route::get('/posts/', 'PostsController@index');
Route::get('/posts/create', 'PostsController@create');
Route::get('/posts/{post}', 'PostsController@show');
Route::post('/posts', 'PostsController@store');

app/Post.php
<?php

namespace App;

use GrahamCampbell\Markdown\Facades\Markdown;
// sw - Removed the use of the Eloquent Model to use my own model that extends the Eloquent Model
//use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    // sw - Removed the protected fillable to and replaced it by using my Model class to create a protected guarded variable
    // sw - This approach requires more checks to make sure unwanted mass assignments are not used
    //protected $fillable = ['title', 'body'];

    public function getBodyHTMLAttribute($value)
    {
        return $this->body ? Markdown::convertToHTML(e($this->body)) : NULL;
    }

    public function getExcerptHTMLAttribute($value)
    {
        return $this->excerpt ? Markdown::convertToHTML(e($this->excerpt)) : NULL;
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use Illuminate\Http\Request;

class PostController extends Controller
{
    public function index()
    {
        //$posts = Post::all();

        return view('posts.index');//, compact('posts'));
    }

    public function show()
    {
        return view('posts.show');
    }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use GrahamCampbell\Markdown\Facades\Markdown;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class PostsController extends Controller
{
    /** Route: GET /posts
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::all();

        return view('posts.index', compact('posts'));
    }

    /** Route: GET /posts/{id}
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        DB::enableQueryLog();
        $post = Post::where('id', '=', $id)->first();
//        dd(DB::getQueryLog(), $post);

        return view('posts.show', compact('post'));
    }

    /** Route: GET /posts/create
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts.create');
    }

    /** Route: POST /posts
     * Store a newly created resource in storage.
     *
     * sw - Removed the paramater of Request to allow the use of mass assignement using the Request Model and not the object
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store()
    {
        Post::create(request(['title', 'body']));

        return redirect('/posts');
    }

    /** Route: GET /posts/id/edit
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /** Route: PATCH /posts/id
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /** Route: DELETE /posts/id
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/posts/create.blade.php
@extends('layouts.master')

@section('content')
<div class="col-md-8 blog-main">
    <h2>Publish a Post</h2>
    <hr>

    <form method="POST" action="/posts">
        {{ csrf_field() }}
        <div class="form-group">
          <label for="postTitle">Title</label>
          <input type="text" name="title" class="form-control" id="postTitle" placeholder="Title">
        </div>
        <div class="form-group">
          <label for="postBody">Body</label>
          <textarea type="textarea" name="body" rows="5 " class="form-control" id="postBody" placeholder="Message"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Publish</button>
    </form>
</div>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.master')

@section('content')
<div class="col-md-8 blog-main">
  <h3 class="pb-4 mb-4 font-italic border-bottom">
    From the Firehose
  </h3>

  @foreach($posts as $post)
  <div class="blog-post">
    <a href="/posts/{{ $post->id }}"><h2 class="blog-post-title">{{ $post->title }}</h2></a>
    <p class="blog-post-meta">{{ $post->created_at }} by <a href="#">Mark</a></p>

    {!! $post->body_html !!}
  </div><!-- /.blog-post -->
  @endforeach

  <nav class="blog-pagination">
    <a class="btn btn-outline-primary" href="#">Older</a>
    <a class="btn btn-outline-secondary disabled" href="#" tabindex="-1" aria-disabled="true">Newer</a>
  </nav>
</div>
@endsection

@section('footer')

@endsection

resources/views/posts/show.blade.php
@extends('layouts.master')

@section('content')
    <div class="col-md-8 blog-main">
      <div class="blog-post">
        <h2 class="blog-post-title">{{ $post->title }}</h2>

        <p class="blog-post-meta">{{ $post->created_at }} by <a href="#">Mark</a></p>
        <hr>

        {!! $post->body_html !!}
      </div><!-- /.blog-post -->
    </div>
@endsection